### ISSUE TITLE
Add Allegro5 + DAllegro

### ISSUE THREAD

**Issue by katastic** [zhaopuming/awesome-d#20]
Hello. I'm new to Github, so if I'm supposed to actually create my own fork and request it be merged or something, let me know.

Anyhow, Allegro 5, a modern game programming library, supports D through a binding/wrapper. DAllegro5 can be found here:

https://github.com/SiegeLord/DAllegro5

Once Allegro 5 is up and running (make sure you have THE SAME version for both the bindings and Allegro 5) all you have to do is git clone, and compile the tiny bindings, and you're good to go. 

Note: DAllegro5 does not directly support GDC. But it does support LDC, LDC2, and DMD. I do not believe there's a big reason other than the author or authors do not have that compiler.

Thanks.

**Comment by zhaopuming** [comment]
OK, added
