### ISSUE TITLE
Another library for your consideration

### ISSUE THREAD

**Issue by markuslaker** [zhaopuming/awesome-d#21]
You asked for people to submit new libraries via issues.  Would you consider adding <https://github.com/markuslaker/Argon> to your list, when you've had a chance to play with it?  I won't be offended if you don't include it; you have the perfect right to include and exclude whatever you wish.

Thanks,

Markus

**Comment by zhaopuming** [comment]
I've seen your post on D forum. Your lib look good :-) Added to the CommandLine section

**Comment by markuslaker** [comment]
Many thanks.  I appreciate your help.

Best regards, and have a good week,

Markus
