### ISSUE TITLE
I plan to make a request on the forum to interview all D contributors 

### ISSUE THREAD

**Issue by wilzbach** [zhaopuming/awesome-d#24]
> YOU - Please add your information if you've done something interesting in D. It is you, the awesome people that made D awesome. Also, I plan to make a request on the forum to interview all D contributors and complete this List.

Please do :)

**Comment by wilzbach** [comment]
Ping!

**Comment by zhaopuming** [comment]
Sorry for replying this late. I haven't been doing D for sometime and just comeback recently.

It seems that there are already a series of interviews in the official blog, and Michael Parker is planning on more. I'll add links to these interviews.

**Comment by wilzbach** [comment]
No worries, you should ping Mike as help in doing the interviews  is highly welcome :)
